name:                bundleSRTReader
version:             0.1.0.0
github:              "Murzinio/bundleSRTReader"
license:             GPL3
author:              "Murzinio"
maintainer:          "Murzinio"
copyright:           "2018 Murzinio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Grabs SRT paths from Witcher 3 bundles.
# category:            Modding

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Murzinio/bundleSRTReader#readme>

dependencies:
- base >= 4.7 && < 5
- filemanip >= 0.3.6.3
- text >= 1.2.3.0
- timeit >= 2.0
- containers >= 0.5.11.0
- split >= 0.2.3.3

library:
  source-dirs: src

executables:
  bundleSRTReader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bundleSRTReader

tests:
  bundleSRTReader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bundleSRTReader
